Editor:
  LastProjectPath: D:\gitnext\Chained Decos\game\chaineddecos\ChainedDecos.chproject
  LastScenePath: D:\gitnext\Chained Decos\game\chaineddecos\assets/scenes/game_mode_selection.chscene
  LoadLastProjectOnStartup: false
  AutoSaveEnabled: true
  AutoSaveInterval: 300